# PyTorch Basics

This notebook covers everything you need to implement deep learning models.

## 1. Tensors - The Foundation

In [1]:
import torch
import numpy as np

# Creating tensors
x = torch.tensor([1, 2, 3])
y = torch.zeros(3, 4)
z = torch.ones(2, 3, 4)
rand = torch.randn(3, 3)  # Normal distribution
uniform = torch.rand(3, 3)  # Uniform [0, 1]

print(f"Shape: {rand.shape}")
print(f"Dtype: {rand.dtype}")
print(f"Device: {rand.device}")

Shape: torch.Size([3, 3])
Dtype: torch.float32
Device: cpu


In [2]:
# Dtype specification - critical for memory and precision
float32 = torch.tensor([1.0, 2.0], dtype=torch.float32)  # Full precision
float16 = torch.tensor([1.0, 2.0], dtype=torch.float16)  # Half precision
int64 = torch.tensor([1, 2], dtype=torch.int64)

# Type conversion
converted = float32.to(torch.int32)
converted = float32.int()  # Shorthand
converted = float32.float()  # To float32

## 2. Tensor Operations - Matrix Math

In [3]:
# Element-wise operations
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

print(a + b)
print(a * b)  # Element-wise multiplication
print(a / b)
print(a ** 2)
print(torch.sqrt(a))
print(torch.exp(a))
print(torch.log(a))

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])
tensor([1., 4., 9.])
tensor([1.0000, 1.4142, 1.7321])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([0.0000, 0.6931, 1.0986])


In [4]:
# Matrix operations - CRUCIAL for neural networks
A = torch.randn(3, 4)
B = torch.randn(4, 5)

# Matrix multiplication
C = torch.matmul(A, B)  # (3, 4) @ (4, 5) = (3, 5)
C = A @ B  # Shorthand
C = torch.mm(A, B)  # 2D only

# Batch matrix multiplication
batch_A = torch.randn(10, 3, 4)  # 10 matrices of 3x4
batch_B = torch.randn(10, 4, 5)
batch_C = torch.bmm(batch_A, batch_B)  # (10, 3, 5)

# Einstein summation - powerful for complex operations
result = torch.einsum('ij,jk->ik', A, B)  # Matrix mult
result = torch.einsum('bij,bjk->bik', batch_A, batch_B)  # Batch mm

In [7]:
# Reduction operations
x = torch.randn(3, 4)

print(torch.sum(x))  # Sum all elements
print(torch.sum(x, dim=0))  # Sum along dimension 0, shape (4,)
print(torch.sum(x, dim=1))  # Sum along dimension 1, shape (3,)
print(torch.sum(x, dim=1, keepdim=True))  # Keep dimension, shape (3, 1)

print(torch.mean(x, dim=1))
print(torch.max(x, dim=1))  # Returns (values, indices)
print(torch.argmax(x, dim=1))  # Just indices

tensor(5.4764)
tensor([1.7255, 2.4254, 0.8504, 0.4751])
tensor([ 3.7173, -1.6518,  3.4109])
tensor([[ 3.7173],
        [-1.6518],
        [ 3.4109]])
tensor([ 0.9293, -0.4129,  0.8527])
torch.return_types.max(
values=tensor([1.3816, 1.7800, 1.7430]),
indices=tensor([0, 1, 3]))
tensor([0, 1, 3])


## 3. Tensor Reshaping - Essential for Model Building

In [8]:
x = torch.randn(2, 3, 4)

# View vs Reshape
# view: requires contiguous memory, faster
# reshape: works always, may copy data
y = x.view(6, 4)
z = x.reshape(6, 4)

# Flatten
flat = x.view(-1)  # Single dimension
flat = x.flatten()  # Same thing

# Add/remove dimensions
expanded = x.unsqueeze(0)  # Add dimension at position 0: (1, 2, 3, 4)
expanded = x.unsqueeze(-1)  # Add at end: (2, 3, 4, 1)
squeezed = expanded.squeeze()  # Remove all dimensions of size 1

# Transpose
transposed = x.transpose(0, 1)  # Swap dimensions 0 and 1
permuted = x.permute(2, 0, 1)  # Rearrange all dimensions

In [9]:
# Concatenation and stacking
a = torch.randn(2, 3)
b = torch.randn(2, 3)

# Concatenate along existing dimension
cat_dim0 = torch.cat([a, b], dim=0)  # (4, 3)
cat_dim1 = torch.cat([a, b], dim=1)  # (2, 6)

# Stack creates new dimension
stacked = torch.stack([a, b], dim=0)  # (2, 2, 3)
stacked = torch.stack([a, b], dim=1)  # (2, 2, 3) different order

# Split
chunks = torch.chunk(cat_dim0, 2, dim=0)  # Split into 2 chunks
splits = torch.split(cat_dim0, [1, 3], dim=0)  # Split into sizes [1, 3]

## 4. Indexing and Slicing

In [10]:
x = torch.randn(4, 5, 6)

# Basic slicing
print(x[0])  # First element along dim 0
print(x[:, 0])  # First element along dim 1 for all in dim 0
print(x[..., 0])  # Last dimension, first element
print(x[1:3, :, 2:5])  # Ranges

# Advanced indexing
indices = torch.tensor([0, 2, 3])
selected = x[indices]  # Select specific indices

# Boolean masking
mask = x > 0
positive = x[mask]  # All positive elements

# Gather and scatter operations
index = torch.tensor([[0, 1], [1, 2]])
gathered = torch.gather(x[0], 1, index)

tensor([[ 0.2977,  0.3093, -0.5676,  1.2890,  2.0216,  0.9456],
        [-2.4832,  0.0324,  1.9444, -0.9831, -1.0576, -0.0417],
        [-1.5432,  0.6477, -0.0170,  1.4749,  0.1992,  0.4196],
        [ 0.0669,  0.6564, -0.8878,  0.4590,  0.0159,  0.6643],
        [ 0.8004, -0.5513,  0.6521, -0.9602, -0.8585, -0.4964]])
tensor([[ 0.2977,  0.3093, -0.5676,  1.2890,  2.0216,  0.9456],
        [-1.4095, -0.9327, -0.0769, -1.3738, -0.8112,  0.8008],
        [-1.5045, -0.0637, -0.1181,  2.1851, -0.5233, -1.3573],
        [ 1.3383,  0.1205, -0.4734,  1.1805, -0.7199, -0.5900]])
tensor([[ 0.2977, -2.4832, -1.5432,  0.0669,  0.8004],
        [-1.4095,  0.3927,  1.2254, -0.2786, -1.4639],
        [-1.5045,  0.1204,  0.8170,  0.5433, -1.3680],
        [ 1.3383,  0.5061,  0.1319,  1.1355, -0.0813]])
tensor([[[-7.6882e-02, -1.3738e+00, -8.1118e-01],
         [-1.5519e-01, -6.3001e-04,  4.2495e-01],
         [-1.3945e+00,  5.7814e-01, -1.1195e+00],
         [ 1.5772e-01,  2.8573e-01,  6.6378e-01],
 

## 5. Automatic Differentiation - Core of Deep Learning

In [11]:
# Enable gradient tracking
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = torch.tensor([1.0, 1.0], requires_grad=True)

# Forward pass
z = x ** 2 + 3 * y
loss = z.sum()

# Backward pass - compute gradients
loss.backward()

print(f"x.grad: {x.grad}")  # dL/dx = 2*x = [4, 6]
print(f"y.grad: {y.grad}")  # dL/dy = 3 = [3, 3]

x.grad: tensor([4., 6.])
y.grad: tensor([3., 3.])


In [12]:
# Gradient accumulation and zeroing
x = torch.tensor([2.0], requires_grad=True)

for i in range(3):
    y = x ** 2
    y.backward()
    print(f"Iteration {i+1}, grad: {x.grad}")
    x.grad.zero_()  # Must zero gradients manually

Iteration 1, grad: tensor([4.])
Iteration 2, grad: tensor([4.])
Iteration 3, grad: tensor([4.])


In [13]:
# Disabling gradient computation - for inference
x = torch.randn(3, requires_grad=True)

# Method 1: Context manager
with torch.no_grad():
    y = x ** 2
    print(f"y.requires_grad: {y.requires_grad}")  # False

# Method 2: Decorator
@torch.no_grad()
def inference(x):
    return x ** 2

# Method 3: Detach
y = x.detach()  # Creates new tensor without gradient

y.requires_grad: False


## 6. Neural Network Modules - Building Blocks

In [14]:
import torch.nn as nn
import torch.nn.functional as F

# Basic module structure
class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()  # MUST call parent __init__
        
        # Define layers
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
        
    def forward(self, x):
        # Define forward pass
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = SimpleNet(10, 20, 5)
x = torch.randn(32, 10)  # Batch of 32
output = model(x)
print(output.shape)  # (32, 5)

torch.Size([32, 5])


In [15]:
# Common layers
linear = nn.Linear(in_features=10, out_features=20)
conv2d = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, stride=1, padding=1)
conv1d = nn.Conv1d(in_channels=10, out_channels=20, kernel_size=5)
maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
avgpool = nn.AvgPool2d(kernel_size=2)
adaptivepool = nn.AdaptiveAvgPool2d((1, 1))  # Output size

# Normalization layers
batchnorm1d = nn.BatchNorm1d(num_features=20)
batchnorm2d = nn.BatchNorm2d(num_features=64)
layernorm = nn.LayerNorm(normalized_shape=[20])
groupnorm = nn.GroupNorm(num_groups=4, num_channels=64)

# Dropout
dropout = nn.Dropout(p=0.5)
dropout2d = nn.Dropout2d(p=0.5)

# Recurrent layers
rnn = nn.RNN(input_size=10, hidden_size=20, num_layers=2, batch_first=True)
lstm = nn.LSTM(input_size=10, hidden_size=20, num_layers=2, batch_first=True)
gru = nn.GRU(input_size=10, hidden_size=20, num_layers=2, batch_first=True)

# Attention
attention = nn.MultiheadAttention(embed_dim=512, num_heads=8, batch_first=True)

In [16]:
# Activation functions
x = torch.randn(10)

# Functional form - no parameters
relu = F.relu(x)
leaky_relu = F.leaky_relu(x, negative_slope=0.01)
tanh = torch.tanh(x)
sigmoid = torch.sigmoid(x)
softmax = F.softmax(x, dim=-1)
log_softmax = F.log_softmax(x, dim=-1)  # Numerically stable
gelu = F.gelu(x)  # Used in transformers
silu = F.silu(x)  # Swish

# Module form - for use in nn.Module
activation = nn.ReLU()
activation = nn.LeakyReLU(negative_slope=0.01)
activation = nn.GELU()

## 7. Loss Functions

In [17]:
# Classification losses
predictions = torch.randn(32, 10)  # Raw logits
targets = torch.randint(0, 10, (32,))  # Class indices

# Cross entropy (combines log_softmax and NLLLoss)
ce_loss = nn.CrossEntropyLoss()
loss = ce_loss(predictions, targets)

# With class weights
weights = torch.ones(10)
weights[0] = 2.0  # Weight class 0 more
ce_loss_weighted = nn.CrossEntropyLoss(weight=weights)

# Binary classification
bce_loss = nn.BCELoss()  # Requires sigmoid output
bce_with_logits = nn.BCEWithLogitsLoss()  # Takes raw logits

# Regression losses
predictions = torch.randn(32, 1)
targets = torch.randn(32, 1)

mse_loss = nn.MSELoss()
mae_loss = nn.L1Loss()
smooth_l1 = nn.SmoothL1Loss()
huber_loss = nn.HuberLoss()

# Advanced losses
kl_div = nn.KLDivLoss()
nll_loss = nn.NLLLoss()  # Negative log likelihood
ctc_loss = nn.CTCLoss()  # For sequence tasks

## 8. Optimizers

In [18]:
import torch.optim as optim

model = SimpleNet(10, 20, 5)

# Common optimizers
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
optimizer = optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999))
optimizer = optim.AdamW(model.parameters(), lr=0.001, weight_decay=0.01)
optimizer = optim.RMSprop(model.parameters(), lr=0.01)
optimizer = optim.Adagrad(model.parameters(), lr=0.01)

# Different learning rates for different parameters
optimizer = optim.Adam([
    {'params': model.fc1.parameters(), 'lr': 0.001},
    {'params': model.fc2.parameters(), 'lr': 0.0001}
])

# Learning rate schedulers
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)
scheduler = optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.95)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=5)
scheduler = optim.lr_scheduler.OneCycleLR(optimizer, max_lr=0.01, total_steps=1000)

## 9. Training Loop - Complete Example

In [19]:
# Complete training loop structure
def train_epoch(model, train_loader, criterion, optimizer, device):
    model.train()  # Set to training mode
    total_loss = 0
    
    for batch_idx, (data, target) in enumerate(train_loader):
        # Move data to device
        data, target = data.to(device), target.to(device)
        
        # Zero gradients
        optimizer.zero_grad()
        
        # Forward pass
        output = model(data)
        
        # Compute loss
        loss = criterion(output, target)
        
        # Backward pass
        loss.backward()
        
        # Gradient clipping (optional but important)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        
        # Update weights
        optimizer.step()
        
        total_loss += loss.item()
    
    return total_loss / len(train_loader)

def evaluate(model, val_loader, criterion, device):
    model.eval()  # Set to evaluation mode
    total_loss = 0
    correct = 0
    
    with torch.no_grad():  # Disable gradient computation
        for data, target in val_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            loss = criterion(output, target)
            total_loss += loss.item()
            
            # Compute accuracy
            pred = output.argmax(dim=1)
            correct += pred.eq(target).sum().item()
    
    accuracy = correct / len(val_loader.dataset)
    return total_loss / len(val_loader), accuracy

## 10. Data Loading and Batching

In [20]:
from torch.utils.data import Dataset, DataLoader, TensorDataset

# Custom Dataset
class CustomDataset(Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

# Create dataset
data = torch.randn(1000, 10)
labels = torch.randint(0, 5, (1000,))
dataset = CustomDataset(data, labels)

# Or use TensorDataset
dataset = TensorDataset(data, labels)

# Create DataLoader
dataloader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True,
    num_workers=4,  # Parallel data loading
    pin_memory=True,  # Faster GPU transfer
    drop_last=False  # Drop last incomplete batch
)

# Iterate through batches
for batch_data, batch_labels in dataloader:
    print(batch_data.shape, batch_labels.shape)
    break

torch.Size([32, 10]) torch.Size([32])


In [21]:
# Custom collate function for variable length sequences
def collate_fn(batch):
    # batch is list of tuples (data, label)
    data, labels = zip(*batch)
    
    # Pad sequences to same length
    data_padded = torch.nn.utils.rnn.pad_sequence(data, batch_first=True)
    labels = torch.stack(labels)
    
    return data_padded, labels

dataloader = DataLoader(dataset, batch_size=32, collate_fn=collate_fn)

## 11. GPU Usage

In [22]:
# Check GPU availability
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# Move tensors to GPU
x = torch.randn(100, 100)
x_gpu = x.to(device)
x_gpu = x.cuda()  # Shorthand

# Move model to GPU
model = SimpleNet(10, 20, 5)
model = model.to(device)

# Multiple GPUs
if torch.cuda.device_count() > 1:
    model = nn.DataParallel(model)

# Memory management
torch.cuda.empty_cache()  # Free unused memory
print(f"Allocated: {torch.cuda.memory_allocated() / 1e9:.2f} GB")
print(f"Reserved: {torch.cuda.memory_reserved() / 1e9:.2f} GB")

Using device: cuda
GPU: NVIDIA GeForce RTX 4070 Laptop GPU
Memory: 8.18 GB
Allocated: 0.00 GB
Reserved: 0.00 GB


## 12. Advanced: Custom Layers

In [24]:
# Custom layer with learnable parameters
class CustomLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        # Register parameters
        self.weight = nn.Parameter(torch.randn(out_features, in_features))
        self.bias = nn.Parameter(torch.randn(out_features))
    
    def forward(self, x):
        return x @ self.weight.t() + self.bias

# Custom activation function
class CustomActivation(nn.Module):
    def __init__(self, alpha=1.0):
        super().__init__()
        self.alpha = alpha
    
    def forward(self, x):
        return torch.where(x > 0, x, self.alpha * (torch.exp(x) - 1))

## 13. Advanced: Custom Functions

In [25]:
# Custom autograd function for special operations
class CustomFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)  # ReLU
    
    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input

# Use it
custom_relu = CustomFunction.apply

## 14. Common Architectures - Practical Examples

In [26]:
# Convolutional Neural Network
class CNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(128)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(128 * 8 * 8, 512)
        self.fc2 = nn.Linear(512, num_classes)
        self.dropout = nn.Dropout(0.5)
    
    def forward(self, x):
        x = self.pool(F.relu(self.bn1(self.conv1(x))))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = x.view(x.size(0), -1)  # Flatten
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

In [27]:
# Residual Block (ResNet building block)
class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, 
                              stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3,
                              stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_channels)
        
        # Shortcut connection
        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1, 
                         stride=stride, bias=False),
                nn.BatchNorm2d(out_channels)
            )
    
    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)  # Skip connection
        out = F.relu(out)
        return out

In [28]:
# Recurrent Neural Network
class RNNModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, 
                           batch_first=True, dropout=0.5)
        self.fc = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        # Initialize hidden and cell states
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        
        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))
        
        # Use last time step
        out = self.fc(out[:, -1, :])
        return out

In [29]:
# Transformer Encoder Block
class TransformerBlock(nn.Module):
    def __init__(self, embed_dim, num_heads, ff_dim, dropout=0.1):
        super().__init__()
        self.attention = nn.MultiheadAttention(embed_dim, num_heads, 
                                              dropout=dropout, batch_first=True)
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        
        self.ff = nn.Sequential(
            nn.Linear(embed_dim, ff_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(ff_dim, embed_dim),
            nn.Dropout(dropout)
        )
    
    def forward(self, x, mask=None):
        # Self-attention with residual
        attn_out, _ = self.attention(x, x, x, attn_mask=mask)
        x = self.norm1(x + attn_out)
        
        # Feedforward with residual
        ff_out = self.ff(x)
        x = self.norm2(x + ff_out)
        return x

## 15. Mixed Precision Training

In [31]:
from torch.cuda.amp import autocast

# Initialize scaler
scaler = torch.amp.GradScaler()

def train_with_amp(model, train_loader, criterion, optimizer, device):
    model.train()
    
    for data, target in train_loader:
        data, target = data.to(device), target.to(device)
        
        optimizer.zero_grad()
        
        # Forward pass with autocasting
        with autocast():
            output = model(data)
            loss = criterion(output, target)
        
        # Backward pass with gradient scaling
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

## 16. Useful Utilities

In [33]:
# Parameter counting
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

# Weight initialization
def init_weights(m):
    if isinstance(m, nn.Linear):
        torch.nn.init.xavier_uniform_(m.weight)
        if m.bias is not None:
            m.bias.data.fill_(0.01)
    elif isinstance(m, nn.Conv2d):
        torch.nn.init.kaiming_normal_(m.weight, mode='fan_out')

model.apply(init_weights)

# Freeze/unfreeze layers
def freeze_model(model):
    for param in model.parameters():
        param.requires_grad = False

def unfreeze_model(model):
    for param in model.parameters():
        param.requires_grad = True

# Get specific layer outputs (hooks)
activation = {}
def get_activation(name):
    def hook(model, input, output):
        activation[name] = output.detach()
    return hook


## 17. Common Patterns and Best Practices

In [34]:
# Setting random seeds for reproducibility
def set_seed(seed=42):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Early stopping
class EarlyStopping:
    def __init__(self, patience=7, min_delta=0):
        self.patience = patience
        self.min_delta = min_delta
        self.counter = 0
        self.best_loss = None
        self.early_stop = False
    
    def __call__(self, val_loss):
        if self.best_loss is None:
            self.best_loss = val_loss
        elif val_loss > self.best_loss - self.min_delta:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_loss = val_loss
            self.counter = 0

# Model summary
def model_summary(model, input_size):
    def register_hook(module):
        def hook(module, input, output):
            class_name = str(module.__class__).split(".")[-1].split("'")[0]
            module_idx = len(summary)
            
            m_key = f"{class_name}-{module_idx+1}"
            summary[m_key] = {}
            summary[m_key]["input_shape"] = list(input[0].size())
            summary[m_key]["output_shape"] = list(output.size())
            
            params = 0
            if hasattr(module, "weight") and hasattr(module.weight, "size"):
                params += torch.prod(torch.LongTensor(list(module.weight.size())))
            if hasattr(module, "bias") and hasattr(module.bias, "size"):
                params += torch.prod(torch.LongTensor(list(module.bias.size())))
            summary[m_key]["nb_params"] = params
        
        if not isinstance(module, nn.Sequential) and \
           not isinstance(module, nn.ModuleList):
            hooks.append(module.register_forward_hook(hook))
    
    summary = {}
    hooks = []
    
    model.apply(register_hook)
    model(torch.zeros(input_size))
    
    for h in hooks:
        h.remove()
    
    return summary

## 18. Debugging Tips

In [36]:
# Check for NaN/Inf
def check_nan_inf(tensor, name="tensor"):
    if torch.isnan(tensor).any():
        print(f"NaN detected in {name}")
    if torch.isinf(tensor).any():
        print(f"Inf detected in {name}")

# Gradient checking
def check_gradients(model):
    for name, param in model.named_parameters():
        if param.grad is not None:
            print(f"{name}: grad norm = {param.grad.norm().item():.6f}")
            check_nan_inf(param.grad, f"{name}.grad")

# Detect anomalies
torch.autograd.set_detect_anomaly(True)

In [ ]:
# # Profile code
# with torch.autograd.profiler.profile(use_cuda=True) as prof:
#     output = model(input)
#     loss = criterion(output, target)
#     loss.backward()

# print(prof.key_averages().table(sort_by="cuda_time_total"))

## 19. Complete Training Script Template

In [ ]:
def train_model(
    model, 
    train_loader, 
    val_loader, 
    criterion, 
    optimizer, 
    scheduler,
    device,
    num_epochs=100,
    checkpoint_path='checkpoint.pth'
):
    best_val_loss = float('inf')
    early_stopping = EarlyStopping(patience=10)
    
    for epoch in range(num_epochs):
        # Training
        train_loss = train_epoch(model, train_loader, criterion, optimizer, device)
        
        # Validation
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)
        
        # Update learning rate
        if isinstance(scheduler, optim.lr_scheduler.ReduceLROnPlateau):
            scheduler.step(val_loss)
        else:
            scheduler.step()
        
        print(f"Epoch {epoch+1}/{num_epochs}:")
        print(f"  Train Loss: {train_loss:.4f}")
        print(f"  Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")
        print(f"  LR: {optimizer.param_groups[0]['lr']:.6f}")
        
        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            checkpoint = {
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'scheduler_state_dict': scheduler.state_dict(),
                'best_val_loss': best_val_loss,
            }
            torch.save(checkpoint, checkpoint_path)
            print(f"  Saved checkpoint at epoch {epoch+1}")
        
        # Early stopping
        early_stopping(val_loss)
        if early_stopping.early_stop:
            print("Early stopping triggered")
            break
    
    # Load best model
    checkpoint = torch.load(checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    print(f"Training complete. Best val loss: {best_val_loss:.4f}")
    
    return model

## 20. Key Concepts Summary

### Must-Know Concepts:
1. **Tensors**: Understand shapes, dtypes, devices
2. **Autograd**: requires_grad, backward(), zero_grad()
3. **nn.Module**: __init__() and forward() pattern
4. **Data Loading**: Dataset, DataLoader, batching
5. **Training Loop**: forward → loss → backward → step
6. **Optimization**: SGD, Adam, learning rate scheduling
7. **Device Management**: CPU vs GPU, .to(device)

### Architecture Building:
- Linear layers for fully connected networks
- Conv2d for CNNs
- LSTM/GRU for RNNs
- MultiheadAttention for Transformers
- Residual connections for deep networks
- Batch/Layer normalization for training stability

### Best Practices:
- Always set model.train() and model.eval()
- Use torch.no_grad() for inference
- Clip gradients to prevent explosion
- Save checkpoints regularly
- Monitor gradients and activations
- Use mixed precision for speed
- Set random seeds for reproducibility